#same as the parameter for VRC Contact Receiver in unity
parameters: head_touch
#how long should there be between two sentences (second)
sleep_time: 1
#you can set up many sentences here 
#!must follow my format! 
#!When there are punctuation marks or numbers in the sentence, you need to add "" at the beginning and end of the sentence!
sen_t: 
- 你他妈摸我头是吧
- MD天天摸我头
- 摸摸摸天天摸
