#you can set up many sentences and parameter here 
#!must follow my format! 
#!When there are punctuation marks or numbers in the sentence, 
#   you need to add "" at the beginning and end of the sentence!

#parameter(your avatar):
#- sentences
#- sentences
#- "123"
#- "word,word"
#- word word word
#

head_touch: 
- I'm AFK-ing...
- I'm AFK-ing......